### ISSUE TITLE
Local Playback USB

### ISSUE THREAD

**Issue by razzamatazm** [theothernt/AerialDream#1]
I have all of the 4k HDR videos on an external usb drive. I have not changed the names of the files. The app crashes upon setting to local only.

**Comment by theothernt** [comment]
Thanks for testing out the app and reporting the bug. It was a pretty simple bug, the app was crashing because no local videos were found.

I have tested the latest build with local videos both on the Android TV local storage and external USB storage.

If no videos are found, you'll just see a black screen with the time displayed. If there are videos locally, even just 1, it will play.

Also, please remember - the app is looking for particular filenames only. And each video type (SDR, HDR, 4K) have different filenames.

So if you want to use 4K HDR videos, you'll have to 1) set the video type to 4K HDR/HEVC and 2) download only the Apple videos of that type.

An updated APK should be available shortly.

**Comment by razzamatazm** [comment]
Great - thanks for looking into it!

**Comment by theothernt** [comment]
Ok, the APK is up. Please give it a try and let me know how you get on?

https://github.com/theothernt/AerialDream/releases/tag/0.92-preview

**Comment by razzamatazm** [comment]
Works perfectly. I think the setting for which videos you want (1080, 4k, HDR, etc) defaults back to 1080 after changing to local only. Maybe that was my issue? Thank you again for the great app!
